---
- name: Create directory for apt keyrings
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker's official GPG key for Debian
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: (ansible_distribution == "Debian")

- name: Download Docker's official GPG key for Ubuntu
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: (ansible_distribution == "Ubuntu")

- name: Get system architecture
  become: true
  ansible.builtin.command: dpkg --print-architecture
  register: system_arch
  changed_when: false

- name: Get OS release codename
  become: true
  ansible.builtin.shell: . /etc/os-release && echo "$VERSION_CODENAME"
  register: os_codename
  changed_when: false

- name: Add Docker repository to apt sources for Debian
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ os_codename.stdout }} stable"
    filename: docker
    state: present
  when: (ansible_distribution == "Debian")

- name: Add Docker repository to apt sources for Ubuntu
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ os_codename.stdout }} stable"
    filename: docker
    state: present
  when: (ansible_distribution == "Ubuntu")

- name: Update apt package index after adding Docker repository
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Stop and disable Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: false

- name: Stop and disable Docker socket
  become: true
  ansible.builtin.systemd:
    name: docker.socket
    state: stopped
    enabled: false

- name: Remove Docker socket file
  become: true
  ansible.builtin.file:
    path: /var/run/docker.sock
    state: absent

- name: Create User bin dir
  become: true
  become_user: "{{ runner_user }}"
  ansible.builtin.file:
    path: "{{ runner_dir }}/bin"
    state: directory
    mode: "0700"

- name: Create systemd config dir
  become: true
  become_user: "{{ runner_user }}"
  ansible.builtin.file:
    path: "{{ runner_dir }}/.config/systemd/user"
    state: directory
    mode: "0700"

- name: Copy docker systemd service file
  become: true
  become_user: "{{ runner_user }}"
  ansible.builtin.template:
    src: "docker.service.j2"
    dest: "{{ runner_dir }}/.config/systemd/user/docker.service"
    mode: "0644"
  notify: Restart docker
